### PR TITLE
Improved Looks & Responsiveness

### PR DESCRIPTION
**Pull request by saideepd**
- The page has been updated with better looks
- Fixed the page to be according to web page standards
- Also, made the page to be responsive for mobile users
- Fixed the link of logo to link of @bhumijgupta 's link from his repo so as to avoid dangling/broken links in case the other user deletes the forked repo

### CODE REVIEW

**Comment by bhumijgupta** [comment]
@saideepd can you add a screenshot for better visualization of changes

**Comment by saideepd** [comment]
Hey @bhumijgupta Check the below screenshots for the **old site** _(currently hosted on heroku)_ and the **new site** I modified _(on localhost)_

## Old Desktop Site:
Old Desktop Site

## New Desktop Site
Desktop Site

## Old Mobile Site: 
Old Mobile Site

## New Mobile Site:
Mobile Site


Hope this helps you to get a better understanding and this PR gets merged 😃

**Comment by bhumijgupta** [comment]
The designs look great!! Thanks for the contribution

**Comment by saideepd** [comment]
> The designs look great!! Thanks for the contribution

Glad you liked it 😄

**Pull request merged**
