### PR TITLE
Update the ui just a bit

### PR DESCRIPTION
**Pull request by mileslow2**
removed unnecessary words and changed a couple of things

### CODE REVIEW

**Comment by bhumijgupta** [comment]
@mileslow2 can you add a screenshot of your changes here?

**Comment by mileslow2** [comment]
Screen Shot 2019-10-17 at 6 13 30 AM

**Comment by bhumijgupta** [comment]
@mileslow2 please resolve merge conflict

**Comment by bhumijgupta** [comment]
please fix merge conflicts

**Comment by bhumijgupta** [comment]
gentle ping @mileslow2

**Comment by bhumijgupta** [comment]
Closing due to inactivity

**Pull request closed without merging**
